<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OfficeTools.Common\OfficeTools.Common.csproj" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ExcelTools.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

</Project>
